name: flutter_project_generator
description: CLI tool to select the functionality you need and generate a Flutter project.
version: 0.1.0
repository: https://github.com/cos-overclock/flutter-project-generator

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  dart_console: ^4.1.1
  get_it: ^8.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

assets:
  - assets/